### ISSUE TITLE
Add new server

### ISSUE THREAD

**Issue by Powerack** [rotators/fodev-status#13]
Hello,

Remake from fodev.net said me "write here about your server". OK, I writing here.

Name: FOnline Reloaded CZ
IP: game.fonline.cz
Port: 2238
web: www.fonline.cz
forum: forum.fonline.cz

Please add this project to fodev server list / status.

Thanks!

Powerack.

**Comment by wipe2238** [comment]
[Details](https://fodev.net/status/server/reloaded_cz/) button on main page should show up shortly.

**Comment by Powerack** [comment]
Hello,

I am sorry, but you give me link yesterday (15 hours ago), and if I check it today, page still not exist (Invalid Server ID). Where is problem?

**Comment by wipe2238** [comment]
Seems like your browser didn't catch up on changes in config/server data yet, and is still using cached version of those. Try to [refresh cache](https://en.wikipedia.org/wiki/Wikipedia:Bypass_your_cache#Bypassing_cache) if waiting a bit is not an option; i've checked Firefox/Opera and in both [everything](https://i.imgur.com/6bGXhAQ.png) looks [fine](https://i.imgur.com/OTUepJF.png).

**Comment by Powerack** [comment]
I checked it only in Chrome (default). Cache cleaned and page working. Thanks!
