### ISSUE TITLE
Status for Reloaded CZ

### ISSUE THREAD

**Issue by worldremaker** [rotators/fodev-status#15]
Hello,
Due Powerack has left this project I want to ask for changes in Reloaded CZ's status. This one:
![obraz](https://user-images.githubusercontent.com/44644224/109615492-3f924b00-7b34-11eb-8322-3e6b8c78250f.png)

New name: Reloaded S2
New link: reloaded.fonline-aftertimes.net
Website: None
Discord: https://discord.gg/5gxdWMecQ4

Proof:
![obraz](https://user-images.githubusercontent.com/44644224/109615359-1c679b80-7b34-11eb-86b1-eac08b11bf4a.png)

Thank you!

**Comment by wipe2238** [comment]
Done in  aeb4c60. I kept fid ("reloaded_cz") unchanged to keep old data for history graph. That also means details will still use https://fodev.net/status/server/reloaded_cz/ as URL.
Gimme a note if server changed/changes enough to justify cutting ties with CZ legacy and/or you feel it deserves it's own S2 entry ;)

**Comment by worldremaker** [comment]
Thank you!
All CZ translations are now reverted back to EN language and whole gameplay stays in Reloaded S2 style. This project was renamed from CZ to S2 when Powerack managed it, before his leave. No one has problem with it (yet). Check your invitations and see all changes in repository. Hope it will be enough for you. ;)
Cheers!
Rem
